### ISSUE TITLE
🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

### ISSUE THREAD

**Issue by wlofman021** [orbs-network/ton-contract-verifier#215]
🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

_Originally posted by @wlofman021 in https://github.com/tonkeeper/opentonapi/issues/389_

**Comment by arash3121** [comment]
:)

**Comment by Sara59e** [comment]
من دریافتی نداشتم

**Comment by JanKortes212** [comment]
really?

**Comment by JanKortes212** [comment]
hi haw to claim this reward?

**Comment by Aho38wkw** [comment]
31 Tem 2024 Çar 01:25 tarihinde sara59e ***@***.***> şunu
yazdı:

**Comment by Aho38wkw** [comment]
Open

**Comment by Aho38wkw** [comment]
#218

**Comment by ghost** [comment]
Claim now

**Comment by ghost** [comment]
> 🔒Dana Anda aman, setelah transaksi dikonfirmasi, Anda akan menerima +122346,00 BUKAN
> 
> _Awalnya diposting oleh@wlofman021dalam [penjaga ton/opentonapi#389](https://github.com/tonkeeper/myasset)_

**Comment by Sara59e** [comment]
My scam, no money was deposited into my wallet, you just took

**Comment by Sara59e** [comment]
My scam, no money was deposited into my wallet, you just took

**Comment by abebe6890** [comment]
Hello thank you

**Comment by mm8191** [comment]
122346,00

**Comment by mm8191** [comment]
UQDasWTnuOI4srBPkX9pufz71AV6UuJmApkUhAHeD8Kg2dHz

**Comment by arash3121** [comment]
:)

**Comment by abebe6890** [comment]
So good

**Comment by abebe6890** [comment]
Great

**Comment by abebe6890** [comment]
Nice

**Comment by abebe6890** [comment]
Good

**Comment by abebe6890** [comment]
Great

**Comment by abebe6890** [comment]
Great

**Comment by abebe6890** [comment]
Good

**Comment by abebe6890** [comment]
Nice

**Comment by abebe6890** [comment]
Good

**Comment by abebe6890** [comment]
Great

**Comment by abebe6890** [comment]
Great 💯

**Comment by AphichatSrinamngoen** [comment]
ในวันที่ อา. 15 ก.ย. 2024 19:55 น. abebe6890 ***@***.***>
เขียนว่า:

**Comment by Hesii72** [comment]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in [tonkeeper/opentonapi#389](https://github.com/tonkeeper/opentonapi/issues/389)_

12345

**Comment by Hesii72** [comment]
12345

**Comment by Hesii72** [comment]
12345

**Comment by Hesii72** [comment]
12345

**Comment by JanKortes212** [comment]
hi, somebody know what is wrong with this project!? What a problem? Why they don't return the money? thanks in advance!

**Comment by Hamidasl** [comment]
hi, somebody know what is wrong with this project!? What a problem? Why they don't return the money? thanks in advance!
