### ISSUE TITLE
🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

### ISSUE THREAD

**Issue by wlofman021** [orbs-network/ton-contract-verifier#216]
🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

_Originally posted by @wlofman021 in https://github.com/tonkeeper/opentonapi/issues/389_

_Originally posted by @wlofman021 in https://github.com/ton-blockchain/verifier/issues/215_

**Comment by Sara59e** [comment]
تایید تراکنش میکنم

**Comment by Sara59e** [comment]
> 🔒وجوه شما محفوظ است، پس از تایید تراکنش، + 122346,00 NOT دریافت خواهید کرد
> 
> _در اصل توسط@wlofman021در [tonkeeper/opentonapi#389](https://github.com/tonkeeper/opentonapi/issues/389)_
> 
> _در اصل توسط@wlofman021در [شماره 215](https://github.com/ton-blockchain/verifier/issues/215)_

تایید میکنم

**Comment by wlofman021** [comment]
درود چی‌کار‌باید بکنم

**Comment by Bandytas129** [comment]
👍

**Comment by Bandytas129** [comment]
🙂

**Comment by arash3121** [comment]
:)

**Comment by arash3121** [comment]
[](url)

**Comment by Sara59e** [comment]
خب من چطوری باید دریافت کنم

**Comment by Sara59e** [comment]
تایید تراکنش کجا باید انجام بدم که این وجه به کیف پولم بیاد؟

**Comment by Sara59e** [comment]
![Uploading Screenshot_۲۰۲۴۰۷۳۱_۰۲۰۶۰۰_Tonkeeper.jpg…]()

**Comment by ghost** [comment]
🫡

**Comment by Bandytas129** [comment]
Thx

**Comment by Bandytas129** [comment]
:)

**Comment by ghost** [comment]
Oke

Pada tanggal Kam, 15 Agu 2024 20.33, Mzvd ***@***.***>
menulis:

**Comment by ghost** [comment]
I have problem
Hiks 🥲

Pada tanggal Kam, 15 Agu 2024 20.33, Mzvd ***@***.***>
menulis:

**Comment by ghost** [comment]
@ayosaja1234

**Comment by ghost** [comment]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in https://github.com/tonkeeper/opentonapi/issues/389_
> 
> _Originally posted by @wlofman021 in https://github.com/ton-blockchain/verifier/issues/215_

**Comment by Bandytas129** [comment]
Gh

**Comment by Bandytas129** [comment]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in [tonkeeper/opentonapi#389](https://github.com/tonkeeper/opentonapi/issues/389)_
> 
> _Originally posted by @wlofman021 in #215_

**Comment by Arezoo121** [comment]
> درود چی‌کار‌باید بکنم

من هم با این مشکل روبرو شدم لطفا راهنماییم کنید

**Comment by Bandytas129** [comment]
Thx

2024-07-30, an 09:20, arash3121 ***@***.***> rašė:

**Comment by Arezoo121** [comment]
🔒Your funds are safe, once the transaction is confirmed, you will receive + 30003.00 NOT

**Comment by Arezoo121** [comment]
🔒Your funds are safe, once the transaction is confirmed, you will receive + 0.21 TON

**Comment by Arezoo121** [comment]
🔒Your funds are safe, once the transaction is confirmed, you will receive + 30003.00 NOT

Originally posted by @wlofman021 in tonkeeper/opentonapi#389

Originally posted by @wlofman021 in #215

**Comment by Bandytas129** [comment]
Ry

**Comment by Bandytas129** [comment]
Boom

**Comment by Bandytas129** [comment]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in [tonkeeper/opentonapi#389](https://github.com/tonkeeper/opentonapi/issues/389)_
> 
> _Originally posted by @wlofman021 in #215_

Ty

**Comment by meti2098** [comment]
> تایید تراکنش میکنم

تونستین تراکنش رو‌ تایید کنید؟
منم مثل شما همین مشکلو‌دارم

**Comment by droliesamam** [comment]
Ubftñcdtj=@&$etb
