### ISSUE TITLE
سلام چیزی دریافت نکردم 

### ISSUE THREAD

**Issue by Farshadshiri63** [orbs-network/ton-contract-verifier#220]
من ووچر نات کوین از ایردراپ در تلگرام خریدم ولی بعد از تایید و کسر هزینه هیچ پاداشی دریافت نکردم جز این ووچر ۴ تا دیگه هم دارم که هیچ کدوم کار نکردن راهنمایی لطفا
![Screenshot_20240718-044712_Tonkeeper](https://github.com/user-attachments/assets/75455c96-d85c-48ae-9a0a-372e66db9c2a)
![Screenshot_20240718-044728_Tonkeeper](https://github.com/user-attachments/assets/25aee3e0-9253-41d2-9e62-470680e5f905)
![Screenshot_20240718-044848_Tonkeeper](https://github.com/user-attachments/assets/86efaf4a-ec3c-4cdc-b409-ee1a4d4c1315)
![Screenshot_20240718-044819_Tonkeeper](https://github.com/user-attachments/assets/928f4ecb-0396-4d86-870a-c8a9a97c19f9)
![Screenshot_20240718-044833_Tonkeeper](https://github.com/user-attachments/assets/32d1a1d6-905c-4736-b1c2-5742f02496f0)

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @Farshadshiri63

**Comment by Farshadshiri63** [comment]
سلام جواب من را خواهشا بدهید
