### ISSUE TITLE
Tt

### ISSUE THREAD

**Issue by Readmad** [orbs-network/ton-contract-verifier#247]

**Comment by Lisafox24** [comment]
Я делал перевод на другой кошелек свой же но что-то пошло не так! Прошу вернуть назад… адрес кошелька с которого делал перевод NOT
UQDBz9aoeAtQqOGub1HxfmyIWxNOcAokCHpVTim1uNhKIAWa

**Comment by Lisafox24** [comment]
![IMG_6412](https://github.com/user-attachments/assets/061db76b-b075-4339-9aec-408673108919)
